### PR TITLE
Updating to 2.2.6 API

### PR DESCRIPTION
**Pull request by mwvaughn**
We're not running against 2.0.0-SNAPSHOT.

### CODE REVIEW

**Comment by mwvaughn** [comment]
I'd actually be in favor of 2.6 because we're going to adapting AgavePy to use updates, improvements, etc in the codebase represented by 2.2.2+ and we're at 2.2.6 now. v2 implies compatibility with all of "v2", which was never well-defined IMHO.

**Comment by joestubbs** [comment]
I agree. In general, new features will come out with the next minor upgrade and these won't be supported out of the box. It's nice to pin that in the apiVersion. 

(By the way, just for the record it should be 2.2 not 2.6. I messed us up with the first version of my comment :).

**Comment by mwvaughn** [comment]
OK. Let's reject this PR and I'll do another one pinning to 2.2

**Comment by mwvaughn** [comment]
Closing in favor of https://github.com/TACC/agavepy/pull/33

**Pull request closed without merging**
